sfscgiserv(8)
=============

== NAME

sfscgiserv - start HTTP/CGI server for Sauna File System monitoring

== SYNOPSIS

[verse]
*sfscgiserv* [*-H* 'BIND-HOST'] [*-P* 'BIND-PORT'] [*-R* 'ROOT-PATH']
             [*-D* 'DATA-PATH'] [*-t* 'LOCKTIMEOUT'] [*-f* [*-v*]] ['ACTION']

[verse]
*sfscgiserv* *-h*

== DESCRIPTION

 ######################## ! DEPRECATION WARNING ! #########################
 #                                                                        #
 # sfscgiserv service is deprecated, please use saunafs-cgiserv instead. #
 # See manual entry saunafs-cgiserver(8) for details.                    #
 #                                                                        #
 ######################## ! DEPRECATION WARNING ! #########################

*sfscgiserv* is a very simple HTTP server capable of running CGI scripts for Sauna File System
monitoring.

== OPTIONS

*-h*::
print usage information and exit

*-H* 'BIND_HOST'::
local address to listen on (default: any)

*-P* 'BIND_PORT'::
port to listen on (default: 9425)

*-R* 'ROOT_PATH'::
local path to use as HTTP document root (default is CGIDIR set up at configure time)

*-D* 'DATA_PATH'::
local path to store data, e.g. a lockfile (default is DATA_PATH set up at configure time)

*-f*::
run in foreground, don't daemonize

*-v*::
log requests on stderr

*-t* 'LOCKTIMEOUT'::
how long to wait for lockfile (default is 60 seconds)

'ACTION'
is the one of *start*, *stop*, *restart* or *test*. Default action is *restart*.

== COPYRIGHT

Copyright 2008-2009 Gemius SA
Copyright 2013-2019 Skytechnology sp. z o.o.
Copyright 2023      Leil Storage OÜ

SaunaFS is free software: you can redistribute it and/or modify it under the terms of the GNU
General Public License as published by the Free Software Foundation, version 3.

SaunaFS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
Public License for more details.

You should have received a copy of the GNU General Public License along with SaunaFS. If not, see
<http://www.gnu.org/licenses/>.

== SEE ALSO

sfs(7)
