ARG DEBIAN_VERSION=bookworm-20221205
FROM debian:${DEBIAN_VERSION}
ARG DEBIAN_FRONTEND=noninteractive
ENV LC_ALL="C"
ENV TZ=Europe/Warsaw
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone
COPY ./tests/setup_machine.sh /tmp/
COPY ./tests/ci_build/setup-build-machine.sh /tmp/ci_build/
ARG GROUP_ID=1000
ARG USER_ID=1000
ARG USERNAME=jenkins
ARG USER_HOME=/home/${USERNAME}
ENV GROUP_ID=${GROUP_ID}
ENV USER_ID=${USER_ID}
ENV USERNAME=${USERNAME}
ENV GTEST_ROOT=/usr/local
RUN set -e; \
    groupadd -g ${GROUP_ID} ${USERNAME}; \
    useradd -r -m -u ${USER_ID} -g ${GROUP_ID} -d ${USER_HOME} ${USERNAME}; \
    mkdir -p ${USER_HOME}/.cache/ccache; \
    chmod -R ugo+rwX ${USER_HOME}
WORKDIR ${USER_HOME}
ENV VIRTUAL_ENV=/opt/venv
ENV PATH="${VIRTUAL_ENV}/bin:${PATH}"
RUN set -e ; \
    apt-get update ; \
    apt-get install --yes \
      python3-pip \
      python3-setuptools \
      python3-venv \
      python3-wheel ; \
    rm -rf /var/lib/apt/lists/* ; \
    python3 -m venv "${VIRTUAL_ENV}" ; \
    pip install asciidoc
RUN set -e ; \
    apt-get update ; \
    apt-get install --yes sudo ; \
    chmod +x /tmp/ci_build/setup-build-machine.sh ; \
    /tmp/ci_build/setup-build-machine.sh ; \
    rm -rf /var/lib/apt/lists/*
RUN set -e ; \
    apt-get update ; \
    apt-get install --yes \
        lcov \
        tini ; \
    rm -rf /var/lib/apt/lists/*
ENTRYPOINT ["tini", "--"]
