ARG UBUNTU_VERSION=22.04
FROM ubuntu:${UBUNTU_VERSION}
ARG DEBIAN_FRONTEND=noninteractive
ENV LC_ALL="C"
ENV TZ=Europe/Warsaw
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone
COPY ./tests/setup_machine.sh /tmp/
COPY ./tests/ci_build/setup-build-machine.sh /tmp/ci_build/
ARG GROUP_ID=1000
ARG USER_ID=1000
ARG USERNAME=jenkins
ARG USER_HOME=/home/${USERNAME}
ENV GROUP_ID=${GROUP_ID}
ENV USER_ID=${USER_ID}
ENV USERNAME=${USERNAME}

RUN set -e; \
    groupadd -g ${GROUP_ID} ${USERNAME}; \
    useradd -r -m -u ${USER_ID} -g ${GROUP_ID} -d ${USER_HOME} ${USERNAME}; \
    mkdir -p ${USER_HOME}/.cache/ccache; \
    chmod -R ugo+rwX ${USER_HOME}
WORKDIR ${USER_HOME}

RUN set -e ; \
    apt-get update ; \
    chmod +x /tmp/ci_build/setup-build-machine.sh ; \
    /tmp/ci_build/setup-build-machine.sh ; \
    rm -rf /var/lib/apt/lists/*
RUN set -e ; \
    apt-get update ; \
    apt-get install --yes tini ; \
    rm -rf /var/lib/apt/lists/*
ENTRYPOINT ["tini", "--"]
