name: Conventional Commits
on:
  pull_request:
    branches: [ dev ]
jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webiny/action-conventional-commits@v1.3.0
